name: Test Environment Secrets

# Trigger the workflow manually or on push
on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allows manual trigger

jobs:
  test-development-environment:
    runs-on: ubuntu-latest
    environment: development
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Make shell script executable
      run: chmod +x print_secrets.sh
    
    - name: Test Development Environment
      env:
        APP_NAME: ${{ secrets.APP_NAME }}
        API_URL: ${{ secrets.API_URL }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        ENVIRONMENT: development
      run: |
        echo "=== Testing Development Environment ==="
        ./print_secrets.sh
        echo ""
        python3 print_secrets.py

  test-production-environment:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Make shell script executable
      run: chmod +x print_secrets.sh
    
    - name: Test Production Environment
      env:
        APP_NAME: ${{ secrets.APP_NAME }}
        API_URL: ${{ secrets.API_URL }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        ENVIRONMENT: production
      run: |
        echo "=== Testing Production Environment ==="
        ./print_secrets.sh
        echo ""
        python3 print_secrets.py

 